### ISSUE TITLE
Probleme beim Beenden (/end), wenn Spieler online sind

### ISSUE THREAD

**Issue by RedstoneFuture** [RedstoneWorld/RedPlayerInfo#2]
Wenn man den BungeeCord per `/end` stoppt und noch Spieler online sind, werden die Spieler gekickt und dann werden die BC Plugins deaktiviert.

Dies hat hier jedoch zur Folge, dass RedPlayerInfo mit
`Error while saving player K3ntex/b75b4566-7115-4442-bb1c-a42e1c32802d to database!`
und anderen Meldungen reagiert.

https://pastebin.com/UunYjvs4

Ist es möglich, dass man hier ein ordentliches Beenden vollzieht oder eher schwierig?

**Comment by Phoenix616** [comment]
Möglich ist das auf jedenfall, müsste eine Form einer Save-Queue eingebaut werden die das runterfahren verhindert bis alles gespeichert ist anstatt einfach nur wie jetzt das Speichern in einem asynchronen Task nach dem Logout eines Spielers vorzunehmen.

**Comment by RedstoneFuture** [comment]
Ist halt die Frage, wie sinnvoll das ist, das Beenden zu verzögern. Aber eigentlich sagt man ja: lieber etwas Delay reinpacken, als ein Fehler auszugeben.

Oder ich kicke einfach ab sofort jeden Spieler, bevor ich den BC stoppe. (Meist ist das eh aus Debug-Zwecken und klommt nur selten vor.)

Vielleicht kommt das auch bei anderen Plugins besser an, wenn ich nicht einfach nur den BC beende, während noch Spieler drauf sind. In dem Fall musst du hier nichts programmieren.

**Comment by Phoenix616** [comment]
Eigentlich sollte das kein Problem sein da BungeeCord [alle Spieler disconnected](https://github.com/SpigotMC/BungeeCord/blob/b70cb014130ee35641e33f240bcc151343af06b9/proxy/src/main/java/net/md_5/bungee/BungeeCord.java#L412) bevor Plugins disabled werden. Möglicherweise gibts da nen Problem dass das nicht ordentlich funktionier? Kannst du vllt. die originale Fehlermeldung posten (am Besten direkt hier als Comment/Anhang oder auf gist? Pastebin hat das inzwischen gelöscht und ist daher bisschen meh :S)

**Comment by RedstoneFuture** [comment]
-.- hastepin vermeide ich bereits aus genau diesem Grund... Okay, ich poste es in Zukunft hier rein.

Bezüglich dem Fehler ... joa, ich kann es gerade auch nicht replizieren.

Bis auf ein:

```
> 02.22-02:13:46 [SCHWERWIEGEND] [Shutdown Thread] INFO de.redstoneworld.redplayerinfo.lib.hikari.HikariDataSource - HikariPool-1 - Shutdown initiated...
> 02.22-02:13:46 [SCHWERWIEGEND] [Shutdown Thread] INFO de.redstoneworld.redplayerinfo.lib.hikari.HikariDataSource - HikariPool-1 - Shutdown completed.
```

scheint alles gut zu verlaufen. - Seitens BC und seitens Bukkit. Ich schließe dieses Issue hier erstmal und melde mich, wenn es wieder auftritt.

**Comment by Phoenix616** [comment]
Hm, komisch. Die anderen Fehler sind nicht wirklich Fehler (daher auch das zweite INFO) sondern Log-Meldungen von der Library die aus irgendwelchen Gründen nicht den normalen Logger nutzen. (Hab ich sonst bei der Library auch überall und war mir bis jetzt noch nicht wichtig genug da nen Weg zu finden das ordentlich zu machen ^^')

**Comment by RedstoneFuture** [comment]
Ja, richtig. Das hab ich auch bei anderen Plugins von dir - und es stört ja nicht wirklich.
