### ISSUE TITLE
AFK-Nachrichen Spam | Bitte um Debug-Modus

### ISSUE THREAD

**Issue by RedstoneFuture** [RedstoneWorld/RedPlayerInfo#3]
Hi,

wir haben ja gefühlt seit 2 Jahren, das Problem mit einem sich aufhängendem AFK eines Spielers. Der Bug ist sehr selten und daher sehr schlecht zu replizieren, weil es keinerlei Hinweise in der Console gibt.

Spieler-Log:
```
[23:48:45] [Client thread/INFO]: [CHAT] [hs] [Mitglied+] Twixkuchen: N´abend
[23:48:47] [Client thread/INFO]: [CHAT] [?] Twixkuchen wechselte auf den Survival-Server!
[23:48:49] [Client thread/INFO]: [CHAT] [hs] [Mitglied+] KawaHD: abend
[23:48:50] [Client thread/INFO]: [CHAT] [ALL] [Mitglied+] pickupjan: moin
[23:48:55] [Client thread/INFO]: [CHAT] [-] pickupjan ist gerade abwesend. 
[23:48:55] [Client thread/INFO]: [CHAT] [+] pickupjan ist wieder anwesend.
[23:48:55] [Client thread/WARN]: Unknown custom packed identifier: rpi:unsetafk
[23:49:03] [Client thread/INFO]: [CHAT] [-] pickupjan ist gerade abwesend. 
[23:49:03] [Client thread/INFO]: [CHAT] [+] pickupjan ist wieder anwesend.
[23:49:03] [Client thread/WARN]: Unknown custom packed identifier: rpi:unsetafk
[23:49:07] [Client thread/INFO]: [CHAT] [-] TheDayne02 ist gerade abwesend. 
[23:49:07] [Client thread/INFO]: [CHAT] [hs] [Mitglied+] pickupjan: hä
[23:49:08] [Client thread/INFO]: [CHAT] [+] TheDayne02 ist wieder anwesend.
[23:49:10] [Client thread/INFO]: [CHAT] [hs] [Mitglied+] pickupjan: das bin ich net
[23:49:14] [Client thread/INFO]: [CHAT] [-] pickupjan ist gerade abwesend. 
```

Der Spieler ist nicht afk, kommt aber plötzlich den Zustand - laut seiner Aussage schon zu Beginn zu Unrecht. Er fliegt herum und wird von nun an immer wieder in den AFK gesetzt. Im vorgestrigen Fall ging das von 23:48 Uhr - gestern 00:05 Uhr.

Wie gesagt: weder im Bungeecord, noch in der Hauptserver-Log ist zu dieser Zeit ein Fehler vorzufinden. In diesem Fall war der Spieler auch nur auf dem Hauptserver. Die TPS war zumeist bei 20. Es handelt sich um einen ganz normalen Spieler, ohne Admin-Rechte.

Das mit dem `Unknown custom packed identifier: rpi:unsetafk` komt immer - ist also nicht das Problem.

Mein Vorschlag wäre ein Debug-Mode, den ich via `/afk-debug on` anschalten kann (Berechtigung: rwm.redafk.debug) und ich damit in der Console von BC den Server-Namen sehe, die den AFK toggeln, sowie irgendwelche Meta-Informationen, die dir helfen können.

**Comment by Phoenix616** [comment]
Hab ein paar mehr Events hinzugefügt um zu checken ob ein Spieler AFK ist oder nicht und die AFK-Zeit so geändert dass er das als long schickt und nicht als int. Ansonsten sehe ich momentan nicht wirklich was was sowas zur folge haben könnte.

Einen debug modus gibts ja schon (debug in der config, die kannst du ja auch mit `/redplayerinfo --reload` im Betrieb neuladen). Was allerdings neben den debug Meldung noch interessant wäre ist was der Spieler macht während er immer wieder afk gesetzt wird.

**Comment by RedstoneFuture** [comment]
> Was allerdings neben den debug Meldung noch interessant wäre ist was der Spieler macht während er immer wieder afk gesetzt wird.

Zitate des Spielers:

> also als das problem auftrat bin ich geflogen in gm3 und gm1 hab gebaut, abgebaut und we benutzt... nachdem der server neugestartet wurde bin auf na gejoint, da wars auch... und bin dann zu hs wo es immer noch war... dann irgendwann hats aufgehört

Der Hauptserver wurde nach Auftreten des Spielers durch einen Supporter neugestartet. Aber das scheint es nicht behoben zu haben. Möglicherweise hilft da also nur der BC Neustart. Der Spieler hat auch zwischendurch den BC kurz verlassen, um neu zu joinen - das hat auch nicht geholfen.


Danke. - Ich melde mich hier, wenn ich hierzu mehr weiß.

**Comment by RedstoneFuture** [comment]
K3ntex hatte heute das Problem:

BC Log: https://hastebin.com/fowibomose.coffeescript
Spieler Log: https://hastebin.com/utuzamosud.md


Interessanterweise passiert es gerade nur, wenn ein Spieler auf dem Lobby-Server ist. K2ntext ist zu Beginn auf den Lobby gejoint und dann auf dem Hauptserver. Vielleicht war der Wechsel zu schnell.

**Comment by Phoenix616** [comment]
Hm, komisch. Hab nochmal zwei Sachen geändert die sicherstellen dass der Spieler auch ordentlich als aktiv und nicht afk auf dem Minecraft server markiert ist. Bitte schau mal ob das mit Build 64 immer noch auftritt.

**Comment by RedstoneFuture** [comment]
Hier sieht man mal, was da abgeht (in dem Fall mit "Konstruktix"): https://pastebin.com/hHRjqr8a

> 05.23-15:22:44 Konstruktix/80382970-424b-4299-9296-d956beab9e7b is afk for 0 seconds
> 05.23-15:22:49 Received afktime plugin message
> 05.23-15:22:49 RedstoneFuture/ea2f0834-556d-4f3c-9c73-bb96202315df is afk for 7 seconds
> 05.23-15:22:49 Konstruktix/80382970-424b-4299-9296-d956beab9e7b is afk for 10944 seconds
> 05.23-15:22:49 Konstruktix/80382970-424b-4299-9296-d956beab9e7b is now afk
> 05.23-15:22:50 Konstruktix received unsetafk plugin message
> 05.23-15:22:50 Konstruktix/80382970-424b-4299-9296-d956beab9e7b is not afk anymore

Ich würde es noch nicht an der Versionen festmachen, aber:

![2020-05-23_15 27 08](https://user-images.githubusercontent.com/4140635/82731977-9861c700-9d0a-11ea-8621-5b40f85c9749.png)

Er meinte aber das Problem schonmal mit der 1.13.2 gehabt zu haben.

**Comment by RedstoneFuture** [comment]
Es hilft wohl den Lobby-Server neuzustarten. Ich weiß aber nicht, was an der Lobby so besonders sein soll. (Zumal wir das Problem auch schon früher mit anderen Servern hatten.)

**Comment by RedstoneFuture** [comment]
Was auch hilft ist, wenn die Spieler kurz zur Lobby gehen und dann wieder zurückwechseln. Womit ich wieder bei meiner ersten These bin, dass die Spieler zu "kurz" auf dem Lobby-Server sind und das AFK-System damit nicht klarkommt.

**Comment by RedstoneFuture** [comment]
mmh .. vielleicht liegt es auch an unserem [VoidSpawn](https://www.spigotmc.org/resources/voidspawn.19350/): im "Touch" Modus versucht er beim Herunterfallen eines Spielers ihn zur nächsten Stelle hochzuteleportieren. Zwei Spieler mit dem AFK-Bug hatten den Fall, dass die mal irgendwann "steckengeblieben" sind. Während das Plugin immer versucht den Spieler wegzuteleportieren switch er vom Server und das AFK-System macht Ärger. Ich hab mal das umgestellt und werde sehen, ob es hilft.

**Comment by RedstoneFuture** [comment]
Ich kann jetzt gerade nicht testen, aber der Auto-AFK schlägt wohl aktuell nicht mehr aus. Vielleicht stimmt was mit der letzten Änderung der AFK-Detektion nicht.
Wenn ich Zeit habe, schick ich dir den Debug-Log.

**Comment by RedstoneFuture** [comment]
der hört momentan einfach auf:

BC: https://pastebin.com/v6W0CcFc



Interessanterweise gab es `8:42` Uhr auch ein Lag:

Server (hs): https://pastebin.com/9uxKZMX9


![Unbenannt](https://user-images.githubusercontent.com/4140635/84589794-663b1500-ae31-11ea-8023-6c3eeac51cb6.png)

Ansonsten sehe ich keine Hinweise.

**Comment by RedstoneFuture** [comment]
_build 69_

Momentan wird man erst in den AFK-Zustand versetzt, wenn man am längsten online ist oder besser gesagt: es kann immer nur einer direkt abgefragt werden. Im Beispiel war der Account "RedstoneFuture" schon 691 Sek abwesend. Er wurde trotzdem erst in den AFK gesetzt, als der Account "RedstoneInfo" offline gegangen ist.

Dabei ist es egal, ob "RedstoneInfo" afk war oder nicht. - Er ist halt nur der, der schon am längsten auf dem Server war.


Auszug BC:

```
06.23-02:48:47 [INFORMATION] [RedPlayerInfo] RedstoneInfo/947ef9cd-f401-43a1-9f55-e3bc830175ee is afk for 37 seconds
06.23-02:48:47 [INFORMATION] [BungeeChat] LEAVE > hs > RedstoneInfo: §4[-] §fRedstoneInfo §7hat §fRedstoneWorld §7verlassen!
06.23-02:48:47 [INFORMATION] [RedstoneInfo] -> UpstreamBridge has disconnected
06.23-02:48:48 [INFORMATION] [RedstoneInfo] <-> DownstreamBridge <-> [hs] has disconnected
06.23-02:48:57 [INFORMATION] [RedPlayerInfo] Received afktime plugin message
06.23-02:48:57 [INFORMATION] [RedPlayerInfo] RedstoneFuture/ea2f0834-556d-4f3c-9c73-bb96202315df is afk for 691 seconds
06.23-02:48:57 [INFORMATION] [RedPlayerInfo] RedstoneFuture/ea2f0834-556d-4f3c-9c73-bb96202315df is now afk
```

längere Version: https://pastebin.com/TP9M28uh

**Comment by Phoenix616** [comment]
Sollte jetzt richtig funktionieren.

**Comment by RedstoneFuture** [comment]
Sieht schonmal besser aus, danke. Ich beobachte das mal die Tage.
